use anyhow::{Context, Result};
use phf_codegen::Map as PhfMapBuilder;
use std::collections::BTreeMap;
use std::fs;

use crate::iana::Entry;

fn emit_generated_rs(entries: &BTreeMap<String, Entry>) -> Result<()> {
    let mut out = String::new();

    out.push_str("// AUTO-GENERATED by the Mime-inator.\n");
    out.push_str("// Do not edit by hand.\n");
    out.push_str("// Source: IANA Media Types Registry\n\n");
    out.push_str("use crate::{Mime, TopLevel};\n\n");

    for entry in entries.values() {
        let suffix_expr = match &entry.suffix {
            Some(s) => format!("Some(\"{}\")", s),
            None => "None".into(),
        };

        out.push_str(&format!(
            "/// `{}`\n\
             pub const {}: Mime = Mime {{\n    \
                 top: TopLevel::{},\n    \
                 sub: \"{}\",\n    \
                 suffix: {},\n\
             }};\n\n",
            entry.essence, entry.const_name, entry.top_variant, entry.sub, suffix_expr,
        ));
    }

    fs::write("libmime/src/generated.rs", &out).context("failed to write generated.rs")?;
    println!("  Wrote src/generated.rs");
    Ok(())
}

fn emit_generated_map_rs(entries: &BTreeMap<String, Entry>) -> Result<()> {
    let mut sorted: Vec<&Entry> = entries.values().collect();
    sorted.sort_by(|a, b| a.essence.cmp(&b.essence));

    let mut out = String::new();

    out.push_str("// AUTO-GENERATED by the Mime-inator.\n");
    out.push_str("// Do not edit by hand.\n\n");
    out.push_str("use crate::generated::*;\n");
    out.push_str("pub(crate) static MIME_MAP: &[(&str, Mime)] = &[\n");

    for entry in &sorted {
        out.push_str(&format!(
            "    (\"{}\", {}),\n",
            entry.essence, entry.const_name,
        ));
    }

    out.push_str("];\n");

    fs::write("libmime/src/generated_map.rs", &out).context("failed to write generated_map.rs")?;
    println!("  Wrote src/generated_map.rs");
    Ok(())
}

fn emit_generated_phf_rs(entries: &BTreeMap<String, Entry>) -> Result<()> {
    let mut phf = PhfMapBuilder::new();

    for entry in entries.values() {
        phf.entry(&entry.essence, &entry.const_name);
    }

    let mut out = String::new();

    out.push_str("// AUTO-GENERATED by the Mime-inator.\n");
    out.push_str("// Do not edit by hand.\n\n");
    out.push_str("use crate::generated::*;\n");
    out.push_str(&format!(
        "pub(crate) static PHF_MAP: phf::Map<&'static str, Mime> = {};\n",
        phf.build()
    ));

    fs::write("libmime/src/generated_phf.rs", &out).context("failed to write generated_phf.rs")?;
    println!("  Wrote src/generated_phf.rs");
    Ok(())
}

pub(crate) fn generate(entries: &BTreeMap<String, Entry>) -> Result<()> {
    emit_generated_rs(entries)?;
    emit_generated_map_rs(entries)?;
    emit_generated_phf_rs(entries)?;

    Ok(())
}
