use anyhow::{Context, Result};
use phf_codegen::Map as PhfMapBuilder;
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use crate::iana::Entry;

const AUTO_STRING: &str = "\
// AUTO-GENERATED by the Mime-inator.
// Do not edit by hand.
// Source: IANA Media Types Registry

";

const GENERATED_RS: &str = "libmime/src/generated.rs";
const GENERATED_MAP_RS: &str = "libmime/src/generated_map.rs";
const GENERATED_PHF_RS: &str = "libmime/src/generated_phf.rs";

pub(crate) struct Diff {
    pub(crate) changed: bool,
    pub(crate) added: Vec<String>,
    pub(crate) removed: Vec<String>,
}

/// Parse existing generated.rs for const names to diff against.
fn read_existing_consts(path: &str) -> BTreeSet<String> {
    let mut consts = BTreeSet::new();
    if let Ok(content) = fs::read_to_string(path) {
        for line in content.lines() {
            if let Some(rest) = line.strip_prefix("pub const ") {
                if let Some(name) = rest.split(':').next() {
                    consts.insert(name.trim().to_string());
                }
            }
        }
    }
    consts
}

fn build_generated_rs(entries: &BTreeMap<String, Entry>) -> String {
    let mut out = String::new();

    out.push_str(AUTO_STRING);

    for entry in entries.values() {
        let suffix_expr = match &entry.suffix {
            Some(s) => format!("Some(\"{}\")", s),
            None => "None".into(),
        };

        out.push_str(&format!(
            "/// `{}`\n\
             pub const {}: Mime = Mime {{\n    \
                 top: TopLevel::{},\n    \
                 sub: \"{}\",\n    \
                 suffix: {},\n\
             }};\n\n",
            entry.essence, entry.const_name, entry.top_variant, entry.sub, suffix_expr,
        ));
    }

    out
}

fn build_generated_map_rs(entries: &BTreeMap<String, Entry>) -> String {
    let mut sorted: Vec<&Entry> = entries.values().collect();
    sorted.sort_by(|a, b| a.essence.cmp(&b.essence));

    let mut out = String::new();

    out.push_str(AUTO_STRING);
    out.push_str("pub(crate) static MIME_MAP: &[(&str, Mime)] = &[\n");

    for entry in &sorted {
        out.push_str(&format!(
            "    (\"{}\", {}),\n",
            entry.essence, entry.const_name,
        ));
    }

    out.push_str("];\n");

    out
}

fn build_generated_phf_rs(entries: &BTreeMap<String, Entry>) -> String {
    let mut phf = PhfMapBuilder::new();

    for entry in entries.values() {
        phf.entry(&entry.essence, &entry.const_name);
    }

    let mut out = String::new();

    out.push_str(AUTO_STRING);
    out.push_str(&format!(
        "pub(crate) static PHF_MAP: phf::Map<&'static str, Mime> \
         = {};\n",
        phf.build()
    ));

    out
}

fn write_file(path: &str, content: &str) -> Result<()> {
    if let Some(parent) = Path::new(path).parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }
    fs::write(path, content).with_context(|| format!("failed to write {}", path))?;
    info!("  Wrote {}", path);
    Ok(())
}

pub(crate) fn generate(entries: &BTreeMap<String, Entry>) -> Result<Diff> {
    // Read existing consts before overwriting
    let old_consts = read_existing_consts(GENERATED_RS);
    let new_consts: BTreeSet<String> = entries.keys().cloned().collect();

    let added: Vec<String> = new_consts.difference(&old_consts).cloned().collect();
    let removed: Vec<String> = old_consts.difference(&new_consts).cloned().collect();

    // Build all output
    let generated = build_generated_rs(entries);
    let generated_map = build_generated_map_rs(entries);
    let generated_phf = build_generated_phf_rs(entries);

    // Check if anything actually changed
    let changed = match fs::read_to_string(GENERATED_RS) {
        Ok(existing) => existing != generated,
        Err(_) => true,
    };

    // Write regardless so files are always consistent
    write_file(GENERATED_RS, &generated)?;
    write_file(GENERATED_MAP_RS, &generated_map)?;
    write_file(GENERATED_PHF_RS, &generated_phf)?;

    Ok(Diff {
        changed,
        added,
        removed,
    })
}
