use anyhow::{Context, Result};
use phf_codegen::Map as PhfMapBuilder;
use std::collections::BTreeMap;
use std::fs;

const IANA_BASE: &str = "https://www.iana.org/assignments/media-types";

const CATEGORIES: &[&str] = &[
    "application",
    "audio",
    "font",
    "haptics",
    "image",
    "message",
    "model",
    "multipart",
    "text",
    "video",
];

struct Entry {
    const_name: String,
    top_variant: String,
    sub: String,
    suffix: Option<String>,
    essence: String,
}

/// Turns e.g. ("application", "vnd.api+json") into "APPLICATION_VND_API_JSON"
fn const_name(category: &str, subtype: &str) -> String {
    format!("{}_{}", category, subtype)
        .to_ascii_uppercase()
        .replace(['-', '.', '+', ' '], "_")
}

/// Turns e.g. "application" into "Application"
fn top_variant(category: &str) -> String {
    let mut chars = category.chars();
    match chars.next() {
        Some(c) => format!("{}{}", c.to_uppercase(), chars.as_str()),
        None => String::new(),
    }
}

/// Splits e.g. "vnd.api+json" into ("vnd.api", Some("json"))
fn parse_subtype(raw: &str) -> (String, Option<String>) {
    match raw.rfind('+') {
        Some(pos) => {
            let sub = raw[..pos].to_lowercase();
            let suffix = raw[pos + 1..].to_lowercase();
            (sub, Some(suffix))
        }
        None => (raw.to_lowercase(), None),
    }
}

fn build_essence(category: &str, sub: &str, suffix: &Option<String>) -> String {
    match suffix {
        Some(s) => format!("{}/{}+{}", category, sub, s),
        None => format!("{}/{}", category, sub),
    }
}

async fn fetch_entries(client: &reqwest::Client) -> Result<BTreeMap<String, Entry>> {
    let mut entries = BTreeMap::new();

    for &category in CATEGORIES {
        let url = format!("{}/{}.csv", IANA_BASE, category);
        println!("  Fetching {}", url);

        let body = client
            .get(&url)
            .send()
            .await
            .with_context(|| format!("failed to fetch {}", url))?
            .text()
            .await
            .with_context(|| format!("failed to read body from {}", url))?;

        let mut rdr = csv::ReaderBuilder::new()
            .has_headers(true)
            .flexible(true)
            .from_reader(body.as_bytes());

        for record in rdr.records().flatten() {
            let name = record.get(0).unwrap_or("").trim();

            // Skip empty, malformed, or DEPRECATED/OBSOLETED entries
            if name.is_empty() || name.contains(' ') {
                continue;
            }

            let (sub, suffix) = parse_subtype(name);
            let essence = build_essence(category, &sub, &suffix);
            let entry = Entry {
                const_name: const_name(category, name),
                top_variant: top_variant(category),
                sub,
                suffix,
                essence,
            };

            entries.insert(entry.const_name.clone(), entry);
        }
    }

    Ok(entries)
}

fn emit_generated_rs(entries: &BTreeMap<String, Entry>) -> Result<()> {
    let mut out = String::new();

    out.push_str("// AUTO-GENERATED by the Mime-inator.\n");
    out.push_str("// Do not edit by hand.\n");
    out.push_str("// Source: IANA Media Types Registry\n\n");
    out.push_str("use crate::{Mime, TopLevel};\n\n");

    for entry in entries.values() {
        let suffix_expr = match &entry.suffix {
            Some(s) => format!("Some(\"{}\")", s),
            None => "None".into(),
        };

        out.push_str(&format!(
            "/// `{}`\n\
             pub const {}: Mime = Mime {{\n    \
                 top: TopLevel::{},\n    \
                 sub: \"{}\",\n    \
                 suffix: {},\n\
             }};\n\n",
            entry.essence,
            entry.const_name,
            entry.top_variant,
            entry.sub,
            suffix_expr,
        ));
    }

    fs::write("libmime/src/generated.rs", &out).context("failed to write generated.rs")?;
    println!("  Wrote src/generated.rs");
    Ok(())
}

fn emit_generated_map_rs(entries: &BTreeMap<String, Entry>) -> Result<()> {
    let mut sorted: Vec<&Entry> = entries.values().collect();
    sorted.sort_by(|a, b| a.essence.cmp(&b.essence));

    let mut out = String::new();

    out.push_str("// AUTO-GENERATED by the Mime-inator.\n");
    out.push_str("// Do not edit by hand.\n\n");
    out.push_str("use crate::generated::*;\n");
    out.push_str("pub(crate) static MIME_MAP: &[(&str, Mime)] = &[\n");

    for entry in &sorted {
        out.push_str(&format!(
            "    (\"{}\", {}),\n",
            entry.essence, entry.const_name,
        ));
    }

    out.push_str("];\n");

    fs::write("libmime/src/generated_map.rs", &out)
        .context("failed to write generated_map.rs")?;
    println!("  Wrote src/generated_map.rs");
    Ok(())
}

fn emit_generated_phf_rs(entries: &BTreeMap<String, Entry>) -> Result<()> {
    let mut phf = PhfMapBuilder::new();

    for entry in entries.values() {
        phf.entry(&entry.essence, &entry.const_name);
    }

    let mut out = String::new();

    out.push_str("// AUTO-GENERATED by the Mime-inator.\n");
    out.push_str("// Do not edit by hand.\n\n");
    out.push_str("use crate::generated::*;\n");
    out.push_str(&format!(
        "pub(crate) static PHF_MAP: phf::Map<&'static str, Mime> = {};\n",
        phf.build()
    ));

    fs::write("libmime/src/generated_phf.rs", &out)
        .context("failed to write generated_phf.rs")?;
    println!("  Wrote src/generated_phf.rs");
    Ok(())
}

#[tokio::main]
async fn main() -> Result<()> {
    println!("Mime-inator activated!");
    println!();

    println!("Fetching IANA registry...");
    let client = reqwest::Client::builder()
        .user_agent("mime-inator/0.1.0")
        .build()?;

    let entries = fetch_entries(&client).await?;
    println!();
    println!("Found {} MIME types", entries.len());
    println!();

    println!("Generating code...");
    emit_generated_rs(&entries)?;
    emit_generated_map_rs(&entries)?;
    emit_generated_phf_rs(&entries)?;

    println!();
    println!(
        "Mime-inator complete! \
         Behold, {} MIME types of the entire tri-state area!",
        entries.len()
    );

    Ok(())
}
